packages:  # all packages in subdirs of packages/ and components/  - 'packages/**'
  - "src/scripts/**/"
  - "src/themes/tlp/"
  - "src/"
  - "src/themes/BurningParrot"
  - "plugins/**/"
shared-workspace-lockfile: false
