global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: tuleap
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: metrics
      password_file: /metrics_secret.key
    static_configs:
      - targets:
        - web
